server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: root
    password: mingqiyi
    url: jdbc:mysql://127.0.0.1:33307/dream_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml
file:
  upload:
    base-path: D:/images/
    avatar-path: avatars/
    product-path: products/
    temp-path: temp/
    max-file-size: 2097152
    allowed-extensions: jpg,jpeg,png,gif,webp
    thumbnail-width: 200
    thumbnail-height: 200
    avatar-thumbnail-width: 100
    avatar-thumbnail-height: 100
    image-url-prefix: http://localhost:8091/images/
redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
alipay:
  enabled: true
  app_id: 2021000147646288
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCBHX6EDOdsuC9NPfRY8HDJhkAG775n4AFn3aXt4uFPn6RKxnsoylkiW1UIbju/jbWAfd+nn9d4/6K1T37GV2jRHmjaOftVWZExCSg+J4uu7pTVaKu+p2f1qxY69yI4Wf6RHH0gpSaU3lx9j4w3ZiGyToLHvVlKOMjJBAHX1x4M85V2GkT1TS8IJhwQJnD2WQLpu6bLehZ6TWwfBvJy3IEUQH9KR0kA8akpZsdoS+vPurebp+cx0QmKgDBDysNjq5HBAqd5jl+kGlEGmGvNCj65hhMzU1uImDbR7DXq5BDC5S0HSpamyDX991uhT7M5yq6pJ8bj+U4fChcgKL6qNj4BAgMBAAECggEAG0OuJpZO/C88ldQCWBGVz4hQ1uYjT+4GffdZBY3GRDkSyVN2SFvKTK36m8gjR8TV0edCpjPjnUJmCmFaBOoKUTZZr9NUlmZOeYtUeyOApJTuys3KjnztP/w7uoHbMQkX726ToaQeLItz/nOkiUJA1VUs2p7KTxkElSYKeZiMWPF7BvZfErYFsciwyoditBBgpBc7iaqRbaERYxtzJYCGCaTYYaTxYRWOeBO0TOWN6fdmMcTFP9yCyjWlLmDya8i41DxN9thZIRxyuqv3Uo4QkILjBu4KZ5hVy3hFZ1HaRje8nuWoD60FNuzduts9Jhds7uoRwbOzQOxtKiD/8W9q0QKBgQDwvMgBdn2Aiq7gbcEy4233V05czj0HBpEr+Duyq6DTQrMcRm8PDAPoAxZq7LaJs0MgPVxif8XdQxRIGxce/WHj2blhMvXLWZOCnpdRPPp8PViJDeTHWUV3b727EHDGi4b5mQtqvo0GzbwY7NeKXyfunui0qQkKsNqUjO+YAJqNpQKBgQCJTQ+hsBucN5vGdg0qxY5fmgz0u1ObtCNEpLdEIFPm5tPiRnhUe6dzPbFXdWOk+TQM7ECySE+a7GHyjf8xjDT8mL1GSp92DmCg4R6I7u7UjCI6JNH7ujbhuGITDDAcbmtNAJU1ZAVyyGE1DuiqwzTCCBT+SwrPOunvjsMXtS54LQKBgQCQjywjBL4URDMC/aU4I63TCxA5Vnb7Ewx1tNhUUA+BDNp1Li5egL6PwdriVka+pXC3mWEynLt6RF+XdP0LVOhFZGaXYXyLobycgRMoa0+W71eM5VTuCENYlzb9b7/o2bwxgZ+Dd+1DmqNK7F35724RMkdWxPJzAwQelAsD4cjtKQKBgAlzW3MWqx/amAdWEtvx0zXzZZbm2f9qq87Kw66VxxCqrMTzcs7l4AXHplBNzTkKyjFlhaJ/5bLVOHy4l2syqmcEoGqZMlau8KnCNRbZ02if6K8135pDHAn3ZhDHkvwyAYLAWoTdSJ64+i/rwcoXO6drZP6H7cuL05RgsD8Ogo9VAoGBANC4PHdm3YxqyH4MYrcKjf3Xs2evwhdUR5rWtnp8MJbAjI27x7p27E/tQkechOruGfJ3oRWX/p6oeHo4aqjplA4UpPcq73HEUQgZIrJscQrm2joSVu48ljlcFlfGCM+I+QgZ1kSifsAkDhQnIkRI9PWjdbq4vR08wgnMDIF7n712
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApuMqqIKhCKOlgsTsZroEM03ybeFtXVbsGBCdYY6f3OOBhpKnkrJTa8OGEN3FrdMRikhCU+EIS4snJLQ3bdlf8e6n2itMPt4T1aL8hvo0nsbXxEl7i48S4lc2j6UPexwBZDnI08ICCRIKadi0y3S/BJbprz70yI2CORvZv909xwqyRO2N6gXaYo+4JNgmEbB9r4b1Pi5G6y7I5185aZy5umTLKGw2ZBUjAkne9BWeQBdKTUj6MxeUEyuqMfDCmmTSZfm5heyKjPbsYUpxx6SsvwqE3Ln8PFp4udQPcE+mLUztImJtT5A4ERtw3o/i2hwUo54Fd8irs5UJ7I6gi0GRfwIDAQAB
  notify_url: http://mmko.natapp1.cc/order/alipay_notify_url
  return_url: http://mmko.natapp1.cc/order/payment/result
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
# RocketMQ 配置
rocketmq:
  name-server: localhost:9876
  producer:
    group: dream-shop-producer
    send-message-timeout: 3000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
    # 添加这些配置提高稳定性
    retry-next-server: true
    access-channel: LOCAL
    # 应用层面禁用VIP通道
    vip-channel-enabled: false
  consumer:
    group: dream-shop-consumer
    consume-timeout: 15000
    consume-thread-min: 5
    consume-thread-max: 32
    suspend-current-queue-time-millis: 1000
    max-reconsume-times: 3
    # 添加这些配置提高性能
    pull-batch-size: 32
    consume-message-batch-max-size: 1
    access-channel: LOCAL
    # 应用层面禁用VIP通道
    vip-channel-enabled: false

logging:
  level:
    root: info
  config: classpath:logback-spring.xml