spring:
  config:
    name: dream-shop-app
  profiles:
    active: dev
  mvc:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations: file:D:/images/
  servlet:

    multipart:
      max-file-size: 10MB
      max-request-size: 10MB